on:
  push:
    branches:
    - main
    - unstable
jobs:
  buildhbm:
      name: Builds HBM RE
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '8'
        - name: Allow running Gradle
          run: chmod u+x ./gradlew
            
        - name: Build with Gradle
          run: ./gradlew build --info

        - name: Upload built jar
          uses: actions/upload-artifact@v4
          with:
            name: Unstable
            path: build/libs
      
